### ISSUE TITLE
503 und Adapter abstürz

### ISSUE THREAD

**Issue by Newan** [Newan/ioBroker.easee#19]
Gemeldet vom warp im Forum
```
2021-07-23 20:34:57.427 - error: easee.0 (11928) Error: Request failed with status code 503
--
  | 2021-07-23 20:34:57.649 - error: easee.0 (11928) Error: Request failed with status code 503
  | 2021-07-23 20:34:57.654 - error: easee.0 (11928) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
  | 2021-07-23 20:34:57.655 - error: easee.0 (11928) unhandled promise rejection: Cannot read property 'cableLocked' of undefined
  | 2021-07-23 20:34:57.656 - error: easee.0 (11928) TypeError: Cannot read property 'cableLocked' of undefined
  | at Easee.setNewStatusToCharger (/opt/iobroker/node_modules/iobroker.easee/main.js:316:85)
  | at async /opt/iobroker/node_modules/iobroker.easee/main.js:207:17
  | 2021-07-23 20:34:57.656 - error: easee.0 (11928) Cannot read property 'cableLocked' of undefined
  | 2021-07-23 20:34:57.671 - warn: easee.0 (11928) Terminated (UNCAUGHT_EXCEPTION): Without reason
  | 2021-07-23 20:34:58.303 - error: host.50a2896d0707 instance system.adapter.easee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
  | 2021-07-23 20:34:58.307 - info: host.50a2896d0707 Restart adapter system.adapter.easee.0 because enabled
  | 2021-07-23 20:35:00.000 - info: javascript.0 (836) script.js.ETA.ETA_5: 22
  | 2021-07-23 20:35:00.005 - info: javascript.0 (836) script.js.Grünbeck.Schleichwasseralarm: 5.6
  | 2021-07-23 20:35:28.356 - info: host.50a2896d0707 instance system.adapter.easee.0 started with pid 30109
  | 2021-07-23 20:35:30.016 - error: easee.0 (30109) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
  | 2021-07-23 20:35:30.018 - error: easee.0 (30109) unhandled promise rejection: Request failed with status code 503
  | 2021-07-23 20:35:30.020 - error: easee.0 (30109) Error: Request failed with status code 503
  | at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)
  | at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:17:12)
  | at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:260:11)
  | at IncomingMessage.emit (events.js:326:22)
  | at endReadableNT (_stream_readable.js:1241:12)
  | at processTicksAndRejections (internal/process/task_queues.js:84:21)
  | 2021-07-23 20:35:30.020 - error: easee.0 (30109) Request failed with status code 503
  | 2021-07-23 20:35:30.037 - warn: easee.0 (30109) Terminated (UNCAUGHT_EXCEPTION): Without reason
  | 2021-07-23 20:35:30.654 - error: host.50a2896d0707 instance system.adapter.easee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
  | 2021-07-23 20:35:30.655 - info: host.50a2896d0707 Restart adapter system.adapter.easee.0 because enabled
  | 2021-07-23 20:36:00.714 - info: host.50a2896d0707 instance system.adapter.easee.0 started with pid 30705
  | 2021-07-23 20:36:02.741 - error: easee.0 (30705) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
  | 2021-07-23 20:36:02.743 - error: easee.0 (30705) unhandled promise rejection: Request failed with status code 503
  | 2021-07-23 20:36:02.745 - error: easee.0 (30705) Error: Request failed with status code 503
  | at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)
  | at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:17:12)
  | at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:260:11)
  | at IncomingMessage.emit (events.js:326:22)
  | at endReadableNT (_stream_readable.js:1241:12)
  | at processTicksAndRejections (internal/process/task_queues.js:84:21)
  | 2021-07-23 20:36:02.746 - error: easee.0 (30705) Request failed with status code 503
  | 2021-07-23 20:36:02.764 - warn: easee.0 (30705) Terminated (UNCAUGHT_EXCEPTION): Without reason
  | 2021-07-23 20:36:03.379 - error: host.50a2896d0707 instance system.adapter.easee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
  | 2021-07-23 20:36:03.380 - info: host.50a2896d0707 Restart adapter system.adapter.easee.0 because enabled
  | 2021-07-23 20:36:03.380 - warn: host.50a2896d0707 Do not restart adapter system.adapter.easee.0 because restart loop detected
  | {1}
```

**Comment by Newan** [comment]
fixed in 1.0.3
